### ISSUE TITLE
Map container is already initialized

### ISSUE THREAD

**Issue by jannisvisser** [mjvanderveen/dashboards#1]
When going to the districtdashboard through navigation, the data will not load, giving the error: "Map container is already initialized". This probably has to do with there also being a leaflet map on the homepage. When you go to the districtdashboard via URL directly (e.g.: also by hard-refreshing the page), this problem doesn't occur.

EDIT: not sure if it has to do with the map on the homepage. The problem also doesn't occur when you navigate to the districtdashboard for the first time (after loading). It only occurs when you move away from the districtdashboard and return (via navigation). 

I think the problem is with the div containing the map (i.e. the "Map container"), which according to some sites (e.g. https://github.com/Leaflet/Leaflet/issues/352), needs to be removed and recreated or something along those lines.

**Comment by mjvanderveen** [comment]
solved

**Comment by jannisvisser** [comment]
How did you solve this? I'm getting the same error again in relation to the zoom-in functionality of different administrative levels.

**Comment by mjvanderveen** [comment]
Please look into the commit history to see the changes that were made.
